services:
  - type: web
    name: propertyleadbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn propertyleadbot_clean.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHON_VERSION
        value: 3.10.12