# Generated by Django 5.2.3 on 2025-06-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("location", models.CharField(max_length=100)),
                ("property_type", models.CharField(max_length=50)),
                ("budget", models.PositiveIntegerField()),
                ("formatted_budget", models.CharField(blank=True, max_length=50)),
                ("raw_query", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
